language: python
python:
  - "3.6"
  - "3.6.5"
install:
  - pip3 install -r requirements.txt
script:
  - pytest DM.py
after_success:
  - mkdir -p coverage
  - codecov --file coverage/lcov.info --disable search