language: python
python:
  - "3.6"
  - "3.6.5"
install:
  - pip3 install -r requirements.txt
script:
  - pytest DM.py
after_success:
  - mkdir -p coverage
  - codecov -t 098a3317-e908-4030-a90c-4fad5c45ad68 --file coverage/lcov.info --disable search